// Generated By J.A.L Converter.

#include <iostream>
#include <cstdlib>
#include <string>
#include <cstdio>
#include <stdexcept>
#if defined(_WIN32) || defined(_WIN64)
#include <windows.h>
#else
#include <unistd.h>
#endif

// Cross-platform sleep function
void jal_sleep(unsigned int seconds) {
#if defined(_WIN32) || defined(_WIN64)
    Sleep(seconds * 1000); // Windows Sleep takes milliseconds
#else
    sleep(seconds); // POSIX sleep takes seconds
#endif
}

// Cross-platform ping function using system calls
void jal_ping(const std::string& target) {
    std::string command;
#if defined(_WIN32) || defined(_WIN64)
    command = "ping -n 1 " + target; // Ping 1 packet on Windows
#else
    command = "ping -c 1 " + target; // Ping 1 packet on POSIX
#endif
    std::cout << "Executing: " << command << std::endl;
    std::system(command.c_str());
}

int main() {
    printf("--- Network Connectivity Test ---\n");
    printf(" \n");
    printf("Pinging Google (8.8.8.8) to check for basic connectivity...\n");
    printf("Pinging 8.8.8.8...\n");
    jal_ping("8.8.8.8");
    printf(" \n");
    printf("This may take a few moments.\n");
    jal_sleep(5);
    printf(" \n");
    printf("Another ping test...\n");
    printf("Pinging www.google.com...\n");
    jal_ping("www.google.com");
    printf(" \n");
    printf("End of network test.\n");
    jal_sleep(5);

    return 0;
}
